"""add vote_count to comments, posts and create new tables

Revision ID: 27e741ed27a1
Revises: 3b7b8c08923a
Create Date: 2024-12-03 01:14:35.540549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e741ed27a1'
down_revision: Union[str, None] = '3b7b8c08923a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('vote_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('vote_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'vote_count')
    op.drop_column('comments', 'vote_count')
    # ### end Alembic commands ###
