"""alter column name student_post_vote_id_v1

Revision ID: 33104d0a095d
Revises: bba0e2e601ce
Create Date: 2024-12-03 01:39:56.300935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33104d0a095d'
down_revision: Union[str, None] = 'bba0e2e601ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
