"""create table stuent_groups

Revision ID: 8b41cbe8b875
Revises: 690ee2c3a029
Create Date: 2024-12-02 18:09:34.494461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b41cbe8b875'
down_revision: Union[str, None] = '690ee2c3a029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_groups',
                    sa.Column('student_group_id',
                              sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.Integer(), nullable=True),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['group_id'], ['groups.group_id'], ),
                    sa.ForeignKeyConstraint(
                        ['student_id'], ['students.student_id'], ),
                    sa.PrimaryKeyConstraint('student_group_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_groups')
    # ### end Alembic commands ###
