"""alter column name student_post_vote_id

Revision ID: bba0e2e601ce
Revises: 57a6469da215
Create Date: 2024-12-03 01:38:17.790122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bba0e2e601ce'
down_revision: Union[str, None] = '57a6469da215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_post_votes', sa.Column('student_post_vote_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('student_post_votes', 'post_vote_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_post_votes', sa.Column('post_vote_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('student_post_votes', 'student_post_vote_id')
    # ### end Alembic commands ###
